# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Civilization.create(id: '1', name: '光')
Civilization.create(id: '2', name: '水')
Civilization.create(id: '3', name: '闇')
Civilization.create(id: '4', name: '火')
Civilization.create(id: '5', name: '自然')


Kind.create(id: '1', name: 'クリーチャー')
Kind.create(id: '2', name: '呪文')


Race.create(id: '1', name: 'エンジェル・コマンド')
Race.create(id: '2', name: 'リキッド・ピープル')
Race.create(id: '3', name: 'リヴァイアサン')
Race.create(id: '4', name: 'デーモン・コマンド')
Race.create(id: '5', name: 'アーマード・ワイバーン')
Race.create(id: '6', name: 'アーマード・ドラゴン')
Race.create(id: '7', name: 'ホーン・ビースト')
Race.create(id: '8', name: 'ジャイアント・インセクト')
Race.create(id: '9', name: 'ガーディアン')
Race.create(id: '10', name: 'バーサーカー')
Race.create(id: '11', name: 'フィッシュ')
Race.create(id: '12', name: 'ダークロード')
Race.create(id: '13', name: 'コロニー・ビートル')
Race.create(id: '14', name: 'ツリー・フォーク')
Race.create(id: '15', name: 'ライトブリンガー')
Race.create(id: '16', name: 'ゲル・フィッシュ')
Race.create(id: '17', name: 'サイバー・ロード')
Race.create(id: '18', name: 'ゴースト')
Race.create(id: '19', name: 'キマイラ')
Race.create(id: '20', name: 'ブレインジャッカー')
Race.create(id: '21', name: 'ドラゴノイド')
Race.create(id: '22', name: 'マシン・イーター')
Race.create(id: '23', name: 'アーマロイド')
Race.create(id: '24', name: 'イニシエート')
Race.create(id: '25', name: 'スターライト・ツリー')
Race.create(id: '26', name: 'サイバー・ウイルス')
Race.create(id: '27', name: 'パラサイトワーム')
Race.create(id: '28', name: 'リビング・デッド')
Race.create(id: '29', name: 'ロック・ビースト')
Race.create(id: '30', name: 'バルーン・マッシュルーム')
Race.create(id: '31', name: 'ブレインジャッカー')
Race.create(id: '32', name: 'ヒューマノイド')
Race.create(id: '33', name: 'ビーストフォーク')


Rarity.create(id: '1', name: 'スーパーレア')
Rarity.create(id: '2', name: 'ベリーレア')
Rarity.create(id: '3', name: 'レア')
Rarity.create(id: '4', name: 'アンコモン')
Rarity.create(id: '5', name: 'コモン')


Power.create(id: '1', value: '0')
Power.create(id: '2', value: '500')
Power.create(id: '3', value: '1000')
Power.create(id: '4', value: '1500')
Power.create(id: '5', value: '2000')
Power.create(id: '6', value: '2500')
Power.create(id: '7', value: '3000')
Power.create(id: '8', value: '3500')
Power.create(id: '9', value: '4000')
Power.create(id: '10', value: '4500')
Power.create(id: '11', value: '5000')
Power.create(id: '12', value: '5500')
Power.create(id: '13', value: '6000')
Power.create(id: '14', value: '6500')
Power.create(id: '15', value: '7000')
Power.create(id: '16', value: '7500')
Power.create(id: '17', value: '8000')
Power.create(id: '18', value: '8500')
Power.create(id: '19', value: '9000')
Power.create(id: '20', value: '9500')
Power.create(id: '21', value: '10000')





Card.create(name: '光輪の精霊シャウナ', kind_id: '1', civilization_id: '1', cost: '7', race_id: '1', power_id: '20', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/93.html')
Card.create(name: '浄化の精霊ウルス', kind_id: '1', civilization_id: '1', cost: '6', race_id: '1', power_id: '13', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/94.html')
Card.create(name: 'アクア・スナイパー', kind_id: '1', civilization_id: '2', cost: '8', race_id: '2', power_id: '11', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/95.html')
Card.create(name: 'キング・オリオン', kind_id: '1', civilization_id: '2', cost: '7', race_id: '3', power_id: '13', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/96.html')
Card.create(name: '混沌の獅子デスライガー', kind_id: '1', civilization_id: '3', cost: '7', race_id: '4', power_id: '19', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/103.html')
Card.create(name: '暗黒の騎士ザガーン', kind_id: '1', civilization_id: '3', cost: '6', race_id: '4', power_id: '15', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/105.html')
Card.create(name: 'クリムゾン・ワイバーン', kind_id: '1', civilization_id: '4', cost: '8', race_id: '5', power_id: '7', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/106.html')
Card.create(name: 'メテオ・ドラゴン', kind_id: '1', civilization_id: '4', cost: '7', race_id: '6', power_id: '9', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/145.html')
Card.create(name: '咆哮するグレート・ホーン', kind_id: '1', civilization_id: '5', cost: '7', race_id: '7', power_id: '17', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/146.html')
Card.create(name: 'デスブレード・ビートル', kind_id: '1', civilization_id: '5', cost: '5', race_id: '8', power_id: '7', rarity_id: '1', url: 'https://www27.atwiki.jp/duel_masters/pages/43.html')
Card.create(name: '天空の守護者グラン・ギューレ', kind_id: '1', civilization_id: '1', cost: '6', race_id: '9', power_id: '19', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/147.html')
Card.create(name: '真理の伝道師レイーラ', kind_id: '1', civilization_id: '1', cost: '6', race_id: '10', power_id: '7', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/148.html')
Card.create(name: 'キング・ポセイドン', kind_id: '1', civilization_id: '2', cost: '7', race_id: '3', power_id: '11', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/150.html')
Card.create(name: 'シーマイン', kind_id: '1', civilization_id: '2', cost: '6', race_id: '11', power_id: '9', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/151.html')
Card.create(name: '妖姫シルフィ', kind_id: '1', civilization_id: '3', cost: '8', race_id: '12', power_id: '9', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/154.html')
Card.create(name: 'ギガルゴン', kind_id: '1', civilization_id: '3', cost: '8', race_id: '9', power_id: '7', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/155.html')
Card.create(name: 'ガトリング・ワイバーン', kind_id: '1', civilization_id: '4', cost: '7', race_id: '5', power_id: '15', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/24.html')
Card.create(name: 'ボルシャック・ドラゴン', kind_id: '1', civilization_id: '4', cost: '6', race_id: '6', power_id: '13', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/40.html')
Card.create(name: 'シェル・タワー', kind_id: '1', civilization_id: '5', cost: '6', race_id: '13', power_id: '11', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/225.html')
Card.create(name: 'トゲ刺しマンドラ', kind_id: '1', civilization_id: '5', cost: '5', race_id: '14', power_id: '9', rarity_id: '2', url: 'https://www27.atwiki.jp/duel_masters/pages/226.html')
Card.create(name: '黄昏の守護者シーブス・キーン', kind_id: '1', civilization_id: '1', cost: '5', race_id: '9', power_id: '13', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/228.html')
Card.create(name: '粛清の伝道師ラー', kind_id: '1', civilization_id: '1', cost: '5', race_id: '10', power_id: '12', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/229.html')
Card.create(name: '月光の守護者ディア・ノーク', kind_id: '1', civilization_id: '1', cost: '4', race_id: '9', power_id: '11', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/230.html')
Card.create(name: '予言者キリアス', kind_id: '1', civilization_id: '1', cost: '4', race_id: '15', power_id: '6', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/232.html')
Card.create(name: 'ホーリー・スパーク', kind_id: '2', civilization_id: '1', cost: '6', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/54.html')
Card.create(name: 'レーザー・ウイング', kind_id: '2', civilization_id: '1', cost: '5', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/234.html')
Card.create(name: 'アクア・ナイト', kind_id: '1', civilization_id: '2', cost: '5', race_id: '2', power_id: '9', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/236.html')
Card.create(name: 'ソーサーヘッド・シャーク', kind_id: '1', civilization_id: '2', cost: '5', race_id: '16', power_id: '7', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/239.html')
Card.create(name: 'トロピコ', kind_id: '1', civilization_id: '2', cost: '5', race_id: '17', power_id: '7', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/240.html')
Card.create(name: '一角魚', kind_id: '1', civilization_id: '2', cost: '4', race_id: '11', power_id: '3', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/242.html')
Card.create(name: 'テレポーテーション', kind_id: '2', civilization_id: '2', cost: '5', race_id: '', power_id: '', rarity_id: '3', url: 'duel_masters')
Card.create(name: 'クリスタル・メモリー', kind_id: '2', civilization_id: '2', cost: '4', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/247.html')
Card.create(name: '滅びの影ナイト・マスター', kind_id: '1', civilization_id: '3', cost: '6', race_id: '18', power_id: '3000', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/249.html')
Card.create(name: 'ギガベロス', kind_id: '1', civilization_id: '3', cost: '5', race_id: '19', power_id: '17', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/250.html')
Card.create(name: 'ギガジール', kind_id: '1', civilization_id: '3', cost: '5', race_id: '19', power_id: '7', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/251.html')
Card.create(name: 'ダーク・クラウン', kind_id: '1', civilization_id: '3', cost: '4', race_id: '20', power_id: '13', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/252.html')
Card.create(name: 'デーモン・ハンド', kind_id: '2', civilization_id: '3', cost: '6', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/44.html')
Card.create(name: 'ブラック・スレイヤー', kind_id: '2', civilization_id: '3', cost: '1', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/263.html')
Card.create(name: '爆勇士ユーカーン', kind_id: '1', civilization_id: '4', cost: '5', race_id: '', power_id: '19', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/264.html')
Card.create(name: 'ドラグライド', kind_id: '1', civilization_id: '4', cost: '5', race_id: '5', power_id: '11', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/266.html')
Card.create(name: '放浪の勇者ジージョ', kind_id: '1', civilization_id: '4', cost: '5', race_id: '22', power_id: '7', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/267.html')
Card.create(name: '銃神兵ディオライオス', kind_id: '1', civilization_id: '4', cost: '4', race_id: '23', power_id: '9', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/268.html')
Card.create(name: 'マグマ・ゲイザー', kind_id: '2', civilization_id: '4', cost: '3', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/269.html')
Card.create(name: 'カオス・ストライク', kind_id: '2', civilization_id: '4', cost: '2', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/270.html')
Card.create(name: 'シェル・ストーム', kind_id: '1', civilization_id: '5', cost: '7', race_id: '13', power_id: '5', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/271.html')
Card.create(name: '群れを守るトライ・ホーン', kind_id: '1', civilization_id: '5', cost: '5', race_id: '7', power_id: '11', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/272.html')
Card.create(name: 'レッドアイ・スコーピオン', kind_id: '1', civilization_id: '5', cost: '5', race_id: '8', power_id: '9', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/273.html')
Card.create(name: '暴走するロング・ホーン', kind_id: '1', civilization_id: '5', cost: '5', race_id: '8', power_id: '9', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/274.html')
Card.create(name: 'ナチュラル・トラップ', kind_id: '2', civilization_id: '5', cost: '6', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/275.html')
Card.create(name: 'オーラ・ブラスター', kind_id: '2', civilization_id: '5', cost: '4', race_id: '', power_id: '', rarity_id: '3', url: 'https://www27.atwiki.jp/duel_masters/pages/276.html')
Card.create(name: '希望の使徒トール', kind_id: '1', civilization_id: '1', cost: '5', race_id: '24', power_id: '5', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/277.html')
Card.create(name: '追跡の使徒ローク', kind_id: '1', civilization_id: '1', cost: '4', race_id: '24', power_id: '9', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/278.html')
Card.create(name: '大気の使徒フレイ', kind_id: '1', civilization_id: '1', cost: '4', race_id: '24', power_id: '7', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/279.html')
Card.create(name: '紅玉草', kind_id: '1', civilization_id: '1', cost: '3', race_id: '25', power_id: '7', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/280.html')
Card.create(name: '予言者カティノ', kind_id: '1', civilization_id: '1', cost: '2', race_id: '15', power_id: '5', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/281.html')
Card.create(name: 'ムーンライト・フラッシュ', kind_id: '2', civilization_id: '1', cost: '4', race_id: '', power_id: '', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/282.html')
Card.create(name: 'ミラージュ・マーメイド', kind_id: '1', civilization_id: '2', cost: '5', race_id: '16', power_id: '9', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/283.html')
Card.create(name: 'リボルバー・フィッシュ', kind_id: '1', civilization_id: '2', cost: '4', race_id: '16', power_id: '9', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/284.html')
Card.create(name: 'フェアリー・チャイルド', kind_id: '1', civilization_id: '2', cost: '4', race_id: '26', power_id: '5', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/285.html')
Card.create(name: 'アクア・ソルジャー', kind_id: '1', civilization_id: '2', cost: '3', race_id: '2', power_id: '3', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/286.html')
Card.create(name: 'キング・クラーケン', kind_id: '1', civilization_id: '2', cost: '3', race_id: '3', power_id: '3', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/287.html')
Card.create(name: 'サイバー・ブレイン', kind_id: '2', civilization_id: '2', cost: '4', race_id: '', power_id: '', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/25.html')
Card.create(name: '腐食虫スワンプワーム', kind_id: '1', civilization_id: '3', cost: '7', race_id: '27', power_id: '5', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/288.html')
Card.create(name: '嘲りの影マスクド・ホラー', kind_id: '1', civilization_id: '3', cost: '5', race_id: '18', power_id: '3', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/289.html')
Card.create(name: '嘆きの影ダーク・レイブン', kind_id: '1', civilization_id: '3', cost: '4', race_id: '18', power_id: '3', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/290.html')
Card.create(name: '捕らえる者ボーン・スパイダー', kind_id: '1', civilization_id: '3', cost: '3', race_id: '28', power_id: '11', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/291.html')
Card.create(name: '凶食虫スティンガーワーム', kind_id: '1', civilization_id: '3', cost: '3', race_id: '27', power_id: '11', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/292.html')
Card.create(name: 'ダーク・リバース', kind_id: '2', civilization_id: '3', cost: '2', race_id: '', power_id: '', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/293.html')
Card.create(name: 'ストーンザウルス', kind_id: '1', civilization_id: '4', cost: '4', race_id: '29', power_id: '9', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/294.html')
Card.create(name: 'メテオザウルス', kind_id: '1', civilization_id: '4', cost: '5', race_id: '29', power_id: '5', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/295.html')
Card.create(name: '走神兵ウルヘリオン', kind_id: '1', civilization_id: '4', cost: '4', race_id: '23', power_id: '7', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/5228.html')
Card.create(name: '超砲手ボルカノドン', kind_id: '1', civilization_id: '4', cost: '4', race_id: '21', power_id: '5', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/297.html')
Card.create(name: '強襲兵ギガントス', kind_id: '1', civilization_id: '4', cost: '3', race_id: '21', power_id: '11', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/298.html')
Card.create(name: 'トルネード・フレーム', kind_id: '2', civilization_id: '4', cost: '5', race_id: '', power_id: '', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/299.html')
Card.create(name: '毒吐きダリア', kind_id: '1', civilization_id: '5', cost: '4', race_id: '14', power_id: '11', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/300.html')
Card.create(name: 'フォレスト・ホーネット', kind_id: '1', civilization_id: '5', cost: '4', race_id: '8', power_id: '9', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/301.html')
Card.create(name: 'からみカズラ', kind_id: '1', civilization_id: '5', cost: '4', race_id: '14', power_id: '7', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/302.html')
Card.create(name: 'シェル・ドーム', kind_id: '1', civilization_id: '5', cost: '4', race_id: '13', power_id: '7', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/303.html')
Card.create(name: 'シビレアシダケ', kind_id: '1', civilization_id: '5', cost: '2', race_id: '30', power_id: '3', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/304.html')
Card.create(name: 'ガイアズ・ソング', kind_id: '2', civilization_id: '5', cost: '1', race_id: '', power_id: '', rarity_id: '4', url: 'https://www27.atwiki.jp/duel_masters/pages/305.html')
Card.create(name: '翡翠樹', kind_id: '1', civilization_id: '1', cost: '3', race_id: '25', power_id: '9', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/306.html')
Card.create(name: '弾丸の使徒イーレ', kind_id: '1', civilization_id: '1', cost: '3', race_id: '24', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/307.html')
Card.create(name: '雷光の使徒ミール', kind_id: '1', civilization_id: '1', cost: '3', race_id: '24', power_id: '3', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/308.html')
Card.create(name: '碧玉草', kind_id: '1', civilization_id: '1', cost: '2', race_id: '25', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/309.html')
Card.create(name: '予言者リュゾル', kind_id: '1', civilization_id: '1', cost: '1', race_id: '15', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/310.html')
Card.create(name: '蒼天の守護者ラ・ウラ・ギガ', kind_id: '1', civilization_id: '1', cost: '1', race_id: '9', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/175.html')
Card.create(name: 'ソニック・ウイング', kind_id: '2', civilization_id: '1', cost: '3', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/311.html')
Card.create(name: 'ソーラー・レイ', kind_id: '2', civilization_id: '1', cost: '2', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/312.html')
Card.create(name: 'ファントム・フィッシュ', kind_id: '1', civilization_id: '2', cost: '4', race_id: '16', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/313.html')
Card.create(name: 'アクア・ハルカス', kind_id: '1', civilization_id: '2', cost: '3', race_id: '2', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/314.html')
Card.create(name: 'キャンディ・ドロップ', kind_id: '1', civilization_id: '2', cost: '3', race_id: '26', power_id: '3', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/315.html')
Card.create(name: '狩猟魚', kind_id: '1', civilization_id: '2', cost: '2', race_id: '11', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/316.html')
Card.create(name: 'アクア・ビークル', kind_id: '1', civilization_id: '2', cost: '2', race_id: '2', power_id: '3', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/317.html')
Card.create(name: 'アクア・ガード', kind_id: '1', civilization_id: '2', cost: '1', race_id: '2', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/318.html')
Card.create(name: 'エレメンタル・トラップ', kind_id: '2', civilization_id: '2', cost: '3', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/176.html')
Card.create(name: 'スパイラル・ゲート', kind_id: '2', civilization_id: '2', cost: '2', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/319.html')
Card.create(name: '汚れた者スケルトンソルジャー', kind_id: '1', civilization_id: '3', cost: '4', race_id: '28', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/320.html')
Card.create(name: '切り裂く者ボーン・アサシン', kind_id: '1', civilization_id: '3', cost: '4', race_id: '28', power_id: '2', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/321.html')
Card.create(name: 'ブラッディ・イヤリング', kind_id: '1', civilization_id: '3', cost: '2', race_id: '31', power_id: '9', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/41.html')
Card.create(name: 'うごめく者ボーン・グール', kind_id: '1', civilization_id: '3', cost: '2', race_id: '28', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/322.html')
Card.create(name: 'さまよう者ブレイン・イーター', kind_id: '1', civilization_id: '3', cost: '2', race_id: '28', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/323.html')
Card.create(name: '怒りの影ブラック・フェザー', kind_id: '1', civilization_id: '3', cost: '1', race_id: '18', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/324.html')
Card.create(name: 'デス・スモーク', kind_id: '2', civilization_id: '3', cost: '4', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/325.html')
Card.create(name: 'ゴースト・タッチ', kind_id: '2', civilization_id: '3', cost: '2', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/326.html')
Card.create(name: '掃討兵バーニング・ヘル', kind_id: '1', civilization_id: '4', cost: '4', race_id: '21', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/26.html')
Card.create(name: '一撃必殺のホーバス', kind_id: '1', civilization_id: '4', cost: '3', race_id: '32', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/327.html')
Card.create(name: '不死身男爵ボーグ', kind_id: '1', civilization_id: '4', cost: '2', race_id: '32', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/328.html')
Card.create(name: '喧嘩屋タイラー', kind_id: '1', civilization_id: '4', cost: '2', race_id: '32', power_id: '3', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/329.html')
Card.create(name: '職人ピコラ', kind_id: '1', civilization_id: '4', cost: '1', race_id: '22', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/330.html')
Card.create(name: '凶戦士ブレイズ・クロー', kind_id: '1', civilization_id: '4', cost: '1', race_id: '21', power_id: '3', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/49.html')
Card.create(name: 'クリムゾン・ハンマー', kind_id: '2', civilization_id: '4', cost: '2', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/331.html')
Card.create(name: 'バーニング・パワー', kind_id: '2', civilization_id: '4', cost: '1', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/332.html')
Card.create(name: '白銀の牙', kind_id: '1', civilization_id: '5', cost: '3', race_id: '33', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/333.html')
Card.create(name: '黄金の翼', kind_id: '1', civilization_id: '5', cost: '3', race_id: '33', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/334.html')
Card.create(name: '無敵の咆哮', kind_id: '1', civilization_id: '5', cost: '3', race_id: '33', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/335.html')
Card.create(name: '青銅の鎧', kind_id: '1', civilization_id: '5', cost: '3', race_id: '33', power_id: '3', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/59.html')
Card.create(name: '鋼鉄の鎚', kind_id: '1', civilization_id: '5', cost: '2', race_id: '33', power_id: '7', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/336.html')
Card.create(name: '炎のたてがみ', kind_id: '1', civilization_id: '5', cost: '2', race_id: '33', power_id: '5', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/337.html')
Card.create(name: 'アルティメット・フォース', kind_id: '2', civilization_id: '5', cost: '5', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/338.html')
Card.create(name: 'ディメンジョン・ゲート', kind_id: '2', civilization_id: '5', cost: '3', race_id: '', power_id: '', rarity_id: '5', url: 'https://www27.atwiki.jp/duel_masters/pages/339.html')
